# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  kuzmichmcc:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - kuzmichmcc

  peer0.kuzmich.example.com:
    container_name: peer0.kuzmich.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.kuzmich.example.com
    networks:
      - kuzmichmcc

  peer1.kuzmich.example.com:
    container_name: peer1.kuzmich.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.kuzmich.example.com
    networks:
      - kuzmichmcc

  peer0.mcc.example.com:
    container_name: peer0.mcc.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.mcc.example.com
    networks:
      - kuzmichmcc

  peer1.mcc.example.com:
    container_name: peer1.mcc.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.mcc.example.com
    networks:
      - kuzmichmcc

  cli.kuzmichmcc:
    container_name: cli.kuzmichmcc
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli.kuzmichmcc
      - CORE_PEER_LOCALMSPID=kuzmich
      - CORE_PEER_ADDRESS=peer0.kuzmich.example.com:7051
#      - CORE_PEER_LOCALMSPID=kuzmich
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/kuzmich.example.com/peers/peer0.kuzmich.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/kuzmich.example.com/peers/peer0.kuzmich.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/kuzmich.example.com/peers/peer0.kuzmich.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/kuzmich.example.com/users/Admin@kuzmich.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
#    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
#        - /home/izolotov/go/src/izolotov/kuzmich-mcc/:/opt/gopath/go/src/izolotov/kuzmich-mcc
        - ./home/izolotov/go/src/izolotov/kuzmich-mcc/:/opt/gopath/src/github.com/izolotov/kuzmich-mcc
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
#        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.kuzmich.example.com
      - peer1.kuzmich.example.com
      - peer0.mcc.example.com
      - peer1.mcc.example.com
    networks:
      - kuzmichmcc
  
